apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversaotemp
  template:
    metadata:
      labels:
        app: conversaotemp
    spec:    
      containers:
      - name: tempcontainer
        image: aledelima/conversao-temperatura:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: tempnodeport
spec:
  selector:
    app: conversaotemp
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000      
      targetPort: 8080
  type: NodePort